###
GET http://localhost:3000/api/db/corecontracts HTTP/1.1
###
GET http://localhost:3000/api/db/corecontracts/626c6e1d5f8c31211997ce5c HTTP/1.1
###
POST http://localhost:3000/api/db/corecontracts HTTP/1.1
content-type: application/json

{
    "key": "auctions",
    "address": "0xc82157De4B27A8D19243f2e07430e3C0880d63E8"
}
###
PUT http://localhost:3000/api/db/corecontracts/626c6e1d5f8c31211997ce5c HTTP/1.1
content-type: application/json

{
    "key": "auctions",
    "address": "0xc82157De4B27A8D19243f2e07430e3C0880d63E9"
}
###
DELETE http://localhost:3000/api/db/corecontracts/626c6e1d5f8c31211997ce5c HTTP/1.1

###
GET http://localhost:3000/api/db/collections HTTP/1.1
###
GET http://localhost:3000/api/db/items HTTP/1.1
###
GET http://localhost:3000/api/db/options HTTP/1.1

###
GET http://localhost:3000/api/erc721/items/ HTTP/1.1

###
GET http://localhost:3000/api/erc721/user HTTP/1.1