POST http://localhost:3000/api/marketplace/admin/corecontract HTTP/1.1
content-type: application/json

{
    "key": "auctions",
    "address": "0xc82157De4B27A8D19243f2e07430e3C0880d63E8"
}
###
GET http://localhost:3000/api/marketplace/admin/corecontract HTTP/1.1
###
GET http://localhost:3000/api/marketplace/admin/corecontract/626c7074c97c1471f96e2e98 HTTP/1.1
###
PUT http://localhost:3000/api/marketplace/admin/corecontract/626c7074c97c1471f96e2e98 HTTP/1.1
content-type: application/json

{
    "key": "auctions",
    "address": "0xc82157De4B27A8D19243f2e07430e3C0880d63E9"
}
###
DELETE http://localhost:3000/api/marketplace/admin/corecontract/626c7074c97c1471f96e2e98 HTTP/1.1
